# Generated by Django 5.2.4 on 2025-07-13 22:40

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', tinymce.models.HTMLField()),
                ('categoria', models.CharField(max_length=50)),
                ('soles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dolares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sustento', models.FileField(upload_to='files/gastos_generales/')),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gasto',
            },
        ),
    ]
