# Generated by Django 5.2.4 on 2025-07-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_generales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
