# Generated by Django 5.2.4 on 2025-07-13 13:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_generales', '0002_gasto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
