# Generated by Django 5.2.4 on 2025-11-03 02:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_generales', '0002_alter_gasto_descripcion_alter_gasto_dolares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
    ]
