# Generated by Django 5.2.4 on 2025-11-03 04:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_generales', '0003_alter_gasto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
    ]
